# Generated by Django 3.0.8 on 2020-08-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('image', models.ImageField(blank=True, upload_to='products_images', verbose_name='Изображение')),
                ('short_desc', models.CharField(blank=True, max_length=100, verbose_name='Краткое описание продукта')),
                ('full_desc', models.TextField(blank=True, verbose_name='Полное описание продукта')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена продукта')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Количество продукта на складе')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductCategory', verbose_name='Название категории')),
            ],
        ),
    ]
