# Generated by Django 3.0.8 on 2020-08-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_merchtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='merch_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.MerchType', verbose_name='Тип мерча'),
        ),
    ]
