# Generated by Django 3.1 on 2020-08-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200821_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='merch_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.merchtype', verbose_name='Тип мерча'),
        ),
    ]
