# Generated by Django 3.1 on 2020-08-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='sex',
            field=models.BooleanField(choices=[(True, 'male'), (False, 'female')], default=True, verbose_name='пол'),
        ),
    ]
