# Generated by Django 3.1 on 2020-08-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_shopuser_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='sex',
            new_name='gender',
        ),
    ]
