# Generated by Django 3.1 on 2020-08-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20200821_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='email',
            field=models.CharField(max_length=100, verbose_name='e-mail'),
        ),
    ]
