# Generated by Django 3.1 on 2020-08-30 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_auto_20200830_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='language',
            field=models.CharField(blank=True, max_length=100, verbose_name='язык'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='social_url',
            field=models.CharField(blank=True, max_length=128, verbose_name='ссылка на соц.сети'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 15, 32, 51, 297892)),
        ),
    ]
