# Generated by Django 3.1 on 2020-09-20 20:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0025_auto_20200920_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='начало')),
                ('end_at', models.DateTimeField(auto_now=True, verbose_name='окончание')),
                ('discount_type', models.CharField(choices=[('MP', 'многоразовая скидка'), ('UP', 'пользовательская скидка'), ('OTP', 'одноразовая скидка'), ('CP', 'купон')], default='MP', max_length=99, verbose_name='тип скидки')),
                ('discount_value', models.PositiveSmallIntegerField(default=0, verbose_name='скидка')),
                ('numbers', models.PositiveIntegerField(blank=True, null=True, verbose_name='количество применений')),
            ],
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 23, 44, 38, 989291)),
        ),
        migrations.CreateModel(
            name='DiscountUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.PositiveIntegerField(blank=True, null=True, verbose_name='оставшееся количество')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discountitems', to='authapp.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discountusers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('discount', 'user')},
            },
        ),
    ]
