# Generated by Django 3.1 on 2020-09-20 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0026_auto_20200920_2344'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discountusers',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='discountusers',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='discountusers',
            name='user',
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 23, 56, 47, 720189)),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='DiscountUsers',
        ),
    ]
